# Generated by Django 4.2.7 on 2025-11-01 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('target_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='目标价格(万元)')),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='当前价格(万元)')),
                ('status', models.CharField(choices=[('active', '激活'), ('triggered', '已触发'), ('cancelled', '已取消')], default='active', max_length=20, verbose_name='状态')),
                ('triggered_at', models.DateTimeField(blank=True, null=True, verbose_name='触发时间')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_alerts', to='houses.house', verbose_name='房源')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_alerts', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '价格提醒',
                'verbose_name_plural': '价格提醒',
                'db_table': 'price_alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='houses.house', verbose_name='房源')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '收藏',
                'verbose_name_plural': '收藏',
                'db_table': 'favorites',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'house')},
            },
        ),
    ]
