# Generated by Django 4.2.7 on 2025-11-01 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(max_length=200, verbose_name='报告标题')),
                ('report_type', models.CharField(choices=[('monthly', '月度报告'), ('quarterly', '季度报告'), ('yearly', '年度报告')], default='monthly', max_length=20, verbose_name='报告类型')),
                ('report_date', models.DateField(verbose_name='报告日期')),
                ('avg_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='平均价格(万元)')),
                ('avg_unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='平均单价(元/平米)')),
                ('total_listings', models.IntegerField(verbose_name='总房源数')),
                ('total_transactions', models.IntegerField(verbose_name='总成交数')),
                ('price_change_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='价格变化率(%)')),
                ('summary', models.TextField(verbose_name='摘要')),
                ('content', models.TextField(blank=True, verbose_name='详细内容')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='market_reports', to='houses.district', verbose_name='区域')),
            ],
            options={
                'verbose_name': '市场报告',
                'verbose_name_plural': '市场报告',
                'db_table': 'market_reports',
                'ordering': ['-report_date'],
            },
        ),
    ]
