# Generated by Django 4.2.7 on 2025-11-01 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='区域名称')),
                ('city', models.CharField(default='上海', max_length=50, verbose_name='城市')),
                ('description', models.TextField(blank=True, verbose_name='区域描述')),
            ],
            options={
                'verbose_name': '区域',
                'verbose_name_plural': '区域',
                'db_table': 'districts',
            },
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(max_length=200, verbose_name='房源标题')),
                ('address', models.CharField(max_length=200, verbose_name='详细地址')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='总价(万元)')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='单价(元/平米)')),
                ('area', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='建筑面积(平米)')),
                ('house_type', models.CharField(choices=[('1室', '1室'), ('2室', '2室'), ('3室', '3室'), ('4室', '4室'), ('5室及以上', '5室及以上')], max_length=20, verbose_name='户型')),
                ('floor', models.CharField(max_length=20, verbose_name='楼层')),
                ('total_floors', models.IntegerField(verbose_name='总楼层')),
                ('orientation', models.CharField(choices=[('东', '东'), ('南', '南'), ('西', '西'), ('北', '北'), ('东南', '东南'), ('东北', '东北'), ('西南', '西南'), ('西北', '西北'), ('南北', '南北')], max_length=10, verbose_name='朝向')),
                ('decoration', models.CharField(default='精装', max_length=50, verbose_name='装修情况')),
                ('build_year', models.IntegerField(blank=True, null=True, verbose_name='建造年份')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='经度')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='纬度')),
                ('description', models.TextField(blank=True, verbose_name='房源描述')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='houses/', verbose_name='封面图')),
                ('status', models.CharField(choices=[('available', '在售'), ('sold', '已售'), ('reserved', '预定')], default='available', max_length=20, verbose_name='状态')),
                ('views', models.IntegerField(default=0, verbose_name='浏览次数')),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_houses', to=settings.AUTH_USER_MODEL, verbose_name='发布经纪人')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='houses', to='houses.district', verbose_name='所属区域')),
            ],
            options={
                'verbose_name': '房源',
                'verbose_name_plural': '房源',
                'db_table': 'houses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deal_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='成交价(万元)')),
                ('deal_date', models.DateField(verbose_name='成交日期')),
                ('buyer_name', models.CharField(blank=True, max_length=50, verbose_name='买家姓名')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='houses.house', verbose_name='房源')),
            ],
            options={
                'verbose_name': '成交记录',
                'verbose_name_plural': '成交记录',
                'db_table': 'transactions',
                'ordering': ['-deal_date'],
            },
        ),
        migrations.CreateModel(
            name='HouseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('image', models.ImageField(upload_to='houses/images/', verbose_name='图片')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='houses.house', verbose_name='所属房源')),
            ],
            options={
                'verbose_name': '房源图片',
                'verbose_name_plural': '房源图片',
                'db_table': 'house_images',
                'ordering': ['order'],
            },
        ),
        migrations.AddIndex(
            model_name='house',
            index=models.Index(fields=['district', 'status'], name='houses_distric_c4b60a_idx'),
        ),
        migrations.AddIndex(
            model_name='house',
            index=models.Index(fields=['price'], name='houses_price_9992b7_idx'),
        ),
        migrations.AddIndex(
            model_name='house',
            index=models.Index(fields=['house_type'], name='houses_house_t_9bcd79_idx'),
        ),
    ]
